# Python Forever!!!
## Computational Methods in Psychology (and Neuroscience)
### Psychology 4500/7559 --- Fall 2020
By: Per B. Sederberg, PhD



# Lesson Objectives

Upon completion of this lesson, students should have learned:

1. State the purpose of modules in Python and identify the common modules
   used in scientific programming

2. Discuss the concepts of *namespace* and variable *scope*

3. Import modules and libraries and use imported functions

4. Create N-dimensional arrays

5. Index values in those arrays

6. Perform operations on those arrays



# Modules

* A **Module** is a file that contains a collection of related functions
* Python has *hundreds* of standard modules
* These are known as the Python Standard Library (http://docs.python.org/library/)
* You can also create and use add-on modules


## Using import

* To use a module, you first have to import it into your namespace
* To import the entire module:

```python
  import module_name
```

* To import specific functions:

```python
  from module_name import function_name
```

## The `math` module

The standard math module includes:

* Number-theoretic and representation functions
* Power and logarithmic functions
* Trigonometric functions
* Hyperbolic functions
* Angular conversion
* Constants


## Using the math module


In [2]:
import math
degrees = 45
radians = (degrees / 360) * 2 * math.pi
print(math.sin(radians))

0.7071067811865475


## Dot notation

* Why did we use ``math.sin()`` instead of just ``sin()``?
* Try this:

In [4]:
print(sin(radians))

NameError: name 'sin' is not defined

* Dot notation allows the Python interpreter to organize and divide the **namespace**

## What not to do...

* Why not just do:
```python
    from math import * 
```

### **Check yourself before you wreck yourself!!!**

* Makes the code harder to read and understand: where do symbols come 
  from?

* Makes it impossible to guess the functionality by the context and
  the name (hint: `os.name` is the name of the OS), and to profit
  usefully from tab completion.

* Restricts the variable names you can use: `os.name` might override 
  `name`, or vise-versa.

* Creates possible name clashes between modules.

* Makes the code impossible to statically check for undefined
  symbols.


## Libraries

* Libraries are simply larger collections of modules.

* We will be exploring a number of libraries, such as ``numpy``, ``scipy``,
  and ``matplotlib`` in this class.


# NumPy (https://numpy.org)

Numerical Analysis in Python


## What is Numpy

**Python** has:

    - built-in: lists, integers, floating point

    - for numerics --- more is needed (efficiency, convenience)

**Numpy** is:

    - extension package to Python for multidimensional arrays

    - closer to hardware (efficiency)

    - designed for scientific computation (convenience)


## For example

An array containing ---

* discretized time of an experiment/simulation

* signal recorded by a measurement device

* pixels of an image

* ...


In [7]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

## The Basics

* NumPy's main object is the homogeneous multidimensional array. 

* It is a table of elements (usually numbers), all of the same type,
  indexed by a tuple of positive integers. 

* In Numpy dimensions are called ''axes''.  The number of axes is ''rank''.

### **For example**

* Coordinates of a point in 3D space `[1, 2, 1]`:

  * Is an array of rank 1, because it has one axis.
  * That axis has a length of 3.


## The ndarray

* Numpy's array class is called `ndarray`. (It is also known by the
  alias `array`.) 

  * **ndarray.ndim**: the number of axes (dimensions) of the array. In
    the Python world, the number of dimensions is referred to as
    ''rank''.

  * **ndarray.shape**: the dimensions of the array. This is a tuple of
    integers indicating the size of the array in each
    dimension.

  * **ndarray.size**: the total number of elements of the array. This is
    equal to the product of the elements of `shape`.

  * **ndarray.dtype**: an object describing the type of the elements in the
    array.

  * **ndarray.itemsize**: the size in bytes of each element of the array. 



## Creating arrays
### 1D arrays

In [11]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [12]:
a.ndim

1

In [13]:
a.shape

(4,)

In [14]:
len(a)

4

## Creating arrays

### 2D, 3D, ....

In [15]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b.shape

(2, 3)

In [17]:
len(b) # returns the size of the first dimension

2

In [18]:
# a 3D array
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [19]:
c.shape

(2, 2, 1)

## In practice

We rarely enter items one by one...

* Evenly spaced:

In [20]:
a = np.arange(10) # 0 .. n-1  (!)
print(a)
b = np.arange(1, 9, 2) # start, end (exlusive), step
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


- or by number of points:

In [21]:
c = np.linspace(0, 1, 6)   # start, end, num-points
print(c)
d = np.linspace(0, 1, 5, endpoint=False)
print(d)

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


## Common arrays



In [27]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [25]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random numbers

Uses the Mersenne Twister pseudo random number generator (PRNG):

In [28]:
a = np.random.rand(4)              # uniform in [0, 1]
a

array([0.41639869, 0.00134999, 0.33074725, 0.83089662])

In [29]:
b = np.random.randn(4)             # Gaussian/normal
b

array([ 0.19730317,  0.27733292, -1.29812388, -1.76774009])

In [30]:
c = np.random.rand(3, 3)           # multiple dimensions
c

array([[0.27365563, 0.7121848 , 0.17829841],
       [0.79088453, 0.87553374, 0.93704718],
       [0.26257238, 0.98724751, 0.21704664]])

## Set the seed

It is possible to set the random number generator seed to get the same
series of numbers generated:

In [31]:
np.random.seed(1234)
print(np.random.rand(3))
np.random.seed(1234)
print(np.random.rand(5))

[0.19151945 0.62210877 0.43772774]
[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]


## Basic data types

You probably noted the ``1`` and ``1.`` above. These are different
data types:


In [37]:
a = np.array([1, 2, 3])
a.dtype


dtype('int64')

In [38]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

Much of the time you don't necessarily need to care, but remember they
are there.


## Choose your own dtype adventure

You can control your data type destiny:


In [40]:
c = np.array([1, 2, 3], dtype=np.float)
c.dtype

dtype('float64')

The **default** data type is floating point:

In [41]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

In [42]:
b = np.linspace(0, 1, 6)
b.dtype

dtype('float64')

## The many choices...

There are also other types:


In [43]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

In [44]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

In [45]:
f = np.array(['Bonjour', 'Hello', 'Hallo', 'Terve', 'Hej'])
f.dtype     # string of max 7 chars

dtype('<U7')

## Indexing and slicing

The items of an array can be accessed and assigned to the same way as
other Python sequences (``list``, ``tuple``):


In [46]:
a = np.arange(10)
print(a)
a[0], a[2], a[-1], a[-2]

[0 1 2 3 4 5 6 7 8 9]


(0, 2, 9, 8)

**Note**: Indices begin at 0, like other Python sequences (and C/C++).
   In contrast, in Fortran or Matlab, indices begin at 1.


## Multidimensional arrays

Indexes are tuples of integers:

In [47]:
a = np.diag(np.arange(5))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [49]:
# read out
print(a[1,1])

# set values
a[2,1] = 10 # third row, second column
a

1


array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0, 10,  2,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  4]])

In [50]:
# read an entire row
a[2]

array([ 0, 10,  2,  0,  0])

## Slicing

Arrays, like other Python sequences can also be sliced:

In [51]:
a = np.arange(10)
a[2:9:3] # [start:end:step]

array([2, 5, 8])

## Indexing and slicing

A small illustrated example of NumPy indexing and slicing:
![](https://scipy-lectures.org/_images/numpy_indexing.png)

## Elementwise operations

With scalars:


In [54]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [55]:
2**a

array([ 2,  4,  8, 16])

All arithmetic operates elementwise:

In [56]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [57]:
a * b

array([2., 4., 6., 8.])

## Warning!

**Multiplication is also elementwise**


In [58]:
c = np.ones((3, 3))
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
# Matrix multiplication via dot product method:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [60]:
# Matrix multiplication operator
c @ c

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

## Comparisons

You can make fast comparisons of ndarrays:


In [62]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [63]:
a > b

array([False, False,  True, False])

## Logical operations

And perform fast logical operations:


In [64]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

a | b

array([ True,  True,  True, False])

In [65]:
a & b

array([ True, False, False, False])

**Note**: For arrays: "``&``" and "``|``" for logical operations, not
   "``and``" and "``or``".


## Shape mismatches

What if things don't line up?


In [66]:
a = np.array([1, 2, 3, 4])
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

**'Broadcast'?** We'll return to that later.

## Basic linear algebra

Matrix multiplication:


In [67]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu) or np.triu?
a

In [69]:
b = np.diag([1, 2, 3])
a.dot(b) # same as `a @ b`

array([[0., 2., 3.],
       [0., 0., 3.],
       [0., 0., 0.]])

## Basic linear algebra

Transpose:

In [70]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

## Basic linear algebra

Inverses and linear equation systems:


In [72]:
A = a + b
A

array([[1., 1., 1.],
       [0., 2., 1.],
       [0., 0., 3.]])

In [74]:
B = np.linalg.inv(A)
B @ A

array([[1.00000000e+00, 0.00000000e+00, 2.77555756e-17],
       [0.00000000e+00, 1.00000000e+00, 2.77555756e-17],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

Eigenvalues:

In [75]:
np.linalg.eigvals(A)

array([1., 2., 3.])

... and so on, see ``np.linalg?``

## Basic reductions

Computing sums:


In [79]:
x = np.array([1, 2, 3, 4])

# called as an object method
x.sum()

10

In [80]:
# or as a module method
np.sum(x)

10

## Sum by rows and by columns



In [81]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [82]:
x.sum(axis=0)

array([3, 3])

In [83]:
x.sum(axis=1)

array([2, 4])

## Other reductions

Work the same way (and take ``axis=``)

- Statistics:


In [85]:
y = np.array([[1, 2, 3], [5, 6, 1]])
np.mean(y, axis=0)

array([3., 4., 2.])

In [86]:
np.median(y, axis=1)

array([2., 5.])

In [87]:
y.std()

1.9148542155126762

## Other reductions

- Extrema:


In [88]:
x = np.array([1, 3, 2])
x.min()

1

In [89]:
x.max()

3

In [91]:
x.argmax()  # index of maximum

1

## Other reductions
- Logical operations

In [92]:
np.all([True, True, False])

False

In [93]:
np.any([True, True, False])

True

## Further reading

- ... and many more (best to learn as you go).

- If you'd like a much more thorough introduction to NumPy, please read the SciPy Lecture Notes: https://scipy-lectures.org/intro/numpy/index.html

## Assignment before next class

- We posted a few assignments on UVACollab
- We'll work on those now for the rest of class, though they are due next week.

You will receive ***points*** for the participation/homework grade by finishing these tasks!

### See you next week!!!